name: CI Pipeline - BYTE Branches and CI Branches

on:
  push:
    branches:
      - 'BYTE*' 
      - 'ci*' 
      - 'teste*' 
      - 'hotfix*' 
  pull_request:
    branches:
      - 'BYTE*' 
      - 'ci*' 
      - 'teste*' 
      - 'hotfix*'   

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: dataviz_bytelabss
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      mysql_test:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD: root
        ports:
           - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven        

      - name: Criar usuário e permissões no MySQL
        run: |
           sleep 20 # Aguarda os serviços do MySQL estarem prontos
            echo "Configurando permissões no MySQL de produção"
            mysql -h 127.0.0.1 -P 3306 -u root -proot -e "CREATE USER IF NOT EXISTS 'userapp'@'%' IDENTIFIED BY 'admin123';"
            mysql -h 127.0.0.1 -P 3306 -u root -proot -e "GRANT ALL PRIVILEGES ON dataviz_bytelabss.* TO 'userapp'@'%'; FLUSH PRIVILEGES;"

            echo "Configurando permissões no MySQL de testes"
            mysql -h 127.0.0.1 -P 3307 -u root -proot -e "CREATE USER IF NOT EXISTS 'userapp'@'%' IDENTIFIED BY 'admin123';"
            mysql -h 127.0.0.1 -P 3307 -u root -proot -e "GRANT ALL PRIVILEGES ON test_db.* TO 'userapp'@'%'; FLUSH PRIVILEGES;"
      - name: Compilar com Maven
        run: mvn clean install --no-transfer-progress

      - name: Executar testes unitários
        run: mvn test --no-transfer-progress

