name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
      - BYTE-121-ci-criar-primeira-versao-pipeline-ci
  pull_request:
    branches:
      - main
      - dev
      - BYTE-121-ci-criar-primeira-versao-pipeline-ci

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
        cache: maven

    - name: Compilar com Maven
      run: mvn clean install --no-transfer-progress

    - name: Executar testes
      run: mvn test --no-transfer-progress
