name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
      - BYTE-121-ci-criar-primeira-versao-pipeline-ci
  pull_request:
    branches:
      - main
      - dev
      - BYTE-121-ci-criar-primeira-versao-pipeline-ci

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: dataviz_bytelabss
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
        cache: maven        

    - name: Run sample.sql
      run: |
        mysql --protocol=tcp -h localhost -P 3306 -u root -proot -e "$(cat $(find ./ -name sample.sql))"

    - name: Compilar com Maven
      run: mvn clean install --no-transfer-progress

    - name: Executar testes
      run: mvn test --no-transfer-progress
